language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - jruby

gemfile:
  - gemfiles/httpclient_nokogiriparser.gemfile
  - gemfiles/httpclient_rexmlparser.gemfile

matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: 2.1.5
    - rvm: jruby

notifications:
  recipients:
    - coder.notify@not404.com

branches:
  only:
    - master

addons:
  code_climate:
    repo_token: ec0b3e0a786f4b93a2522db298c4155c77e25c2137592df0d4f9c2f1a491b89a
